name: PR unit tests

# Triggers the workflow on push or pull request events
on: [push, pull_request]

permissions: read-all

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}-${{github.workflow}}
  cancel-in-progress: true
jobs:

  build:
    name: PR unit tests
    runs-on: macos-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Run tests
      run: |
        make test
