
steps:
# Build the container that will do the go build.
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'builder', '-f', 'Dockerfile.build', '.']
# Do the go build.
  - name: 'builder'
    args: ['make', 'cross']
# Upload to GCS.
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '-r', 'out/*', 'gs://container-structure-test/builds/$COMMIT_SHA/']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/gcp-runtimes/container-structure-test:$COMMIT_SHA', '.']
images:
- 'gcr.io/gcp-runtimes/container-structure-test:$COMMIT_SHA'
