steps:
  - name: gcr.io/cloud-builders/go:latest
    args: ['test', '-c', 'github.com/GoogleCloudPlatform/runtimes-common/structure_tests', '-o', '/workspace/structure_tests/structure_test']
    env: ['PROJECT_ROOT=github.com/GoogleCloudPlatform/runtimes-common']
  - name: gcr.io/cloud-builders/docker:latest
    args: ['build', '-t', '${_IMAGE}', './structure_tests/Dockerfile']
  - name: gcr.io/gcp-runtimes/check_if_tag_exists:latest
    args: ['--image=${_IMAGE}']
images:
  - '${_IMAGE}'
