steps:
# Build the image
  - name: 'gcr.io/cloud-builders/bazel'
    args: ['run', '//:structure_test_image']
# Tag the built image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'bazel:structure_test_image', 'gcr.io/gcp-runtimes/container-structure-test:$TAG_NAME']
# Tag the new image as latest
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'bazel:structure_test_image', 'gcr.io/gcp-runtimes/container-structure-test:latest']
# Build the binary
  - name: 'gcr.io/cloud-builders/bazel'
    args: ['build', '//:container_structure_test']
# Upload the linux binary to GCS
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'bazel-bin/linux_amd64_pure_stripped/container_structure_test', 'gs://container-structure-test/$TAG_NAME/container-structure-test']
# Upload the linux binary to GCS
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'bazel-bin/linux_amd64_pure_stripped/container_structure_test', 'gs://container-structure-test/latest/container-structure-test']

images: [
  'gcr.io/gcp-runtimes/container-structure-test:$TAG_NAME',
  'gcr.io/gcp-runtimes/container-structure-test:latest'
]
