# This build is run on every merge to master.
steps:
# Build the container that will do the go build.
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'builder', '-f', 'deploy/Dockerfile.build', '.']

# Do the go build for amd64
  - name: 'builder-amd64'
    args: ['make', 'cross']
    env: ['GOARCH=amd64']

# Do the go build for arm64
  - name: 'builder-arm64'
    args: ['make', 'cross']
    env: ['GOARCH=arm64']

# Upload to GCS
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '-r', 'out/*', 'gs://container-structure-test/builds/$COMMIT_SHA/']

# Build the image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/gcp-runtimes/container-structure-test:$COMMIT_SHA', 
           '-f', 'deploy/Dockerfile', '.']
images:
- 'gcr.io/gcp-runtimes/container-structure-test:$COMMIT_SHA'
