# Dockerfile used to build a build step that builds container-structure-test in CI.
FROM golang:1.22
RUN apt-get update && apt-get install make
RUN mkdir -p /go/src/github.com/GoogleContainerTools
RUN ln -s /workspace /go/src/github.com/GoogleContainerTools/container-structure-test
WORKDIR /go/src/github.com/GoogleContainerTools/container-structure-test
