# This cloudbuild is run on the creation of new tags, which should signify releases.

steps:
# Build the container that will do the go build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'builder', '-f', 'deploy/Dockerfile.build', '.']

# Do the go build
  - name: 'builder'
    args: ['make', 'cross']

# Upload to GCS
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '-r', 'out/*', 'gs://container-structure-test/$TAG_NAME/']

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '-r', 'gs://container-structure-test/$TAG_NAME/*', 'gs://container-structure-test/latest/']

# Build the image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/gcp-runtimes/container-structure-test:$TAG_NAME',
           '-f', 'deploy/Dockerfile', '.']

# Tag the image as latest
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'gcr.io/gcp-runtimes/container-structure-test:$TAG_NAME',
           'gcr.io/gcp-runtimes/container-structure-test:latest']
  
images:
- 'gcr.io/gcp-runtimes/container-structure-test:$TAG_NAME'
- 'gcr.io/gcp-runtimes/container-structure-test:latest'
